import streamlit as st
# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y8CELQ6d7Y1zfsLwoiezmij_o-JJUuL3
"""

# This tells us if we have the right tools ready
import sys
import os

print(f"Python Version: {sys.version}")
print("Platform Ready: YES")



# BASICS: A variable stores information
candidate_name = "Babu"
skills = "Python, SQL, Technical Process"

# BASICS: A "String Method" changes how text looks
# Imagine a CV has "SQL" but the JD has "sql". We must fix this!
clean_skills = skills.lower()

print(f"Original: {skills}")
print(f"Cleaned (Genuine Logic): {clean_skills}")





# A simple dictionary with two items
test_data = {
    "file_1.txt": "Hello from File 1",
    "file_2.txt": "Hello from File 2"
}

# The Loop: 'name' gets the filename, 'text' gets the message
for name, text in test_data.items():
    with open(name, "w") as f:
        f.write(text)
    print(f"I just automatically created {name}!")

# 1. The Dataset (Dictionary)
# Keys are filenames, Values are the text inside
my_project_files = {
    "JD_Data_Analyst.txt": "Skills: Python, SQL, Power BI, Excel. Location: Pune.",
    "JD_Web_Developer.txt": "Skills: HTML, CSS, JavaScript, Flask. Role: Backend.",
    "JD_Process_Executive.txt": "Skills: Operations, Management, Reporting, Excel.",
    "JD_Python_Dev.txt": "Skills: Python, Django, APIs, PostgreSQL.",
    "JD_Machine_Learning.txt": "Skills: Python, Scikit-learn, Statistics, Math.",
    "CV_Babu.txt": "Name: Babu. Skills: Python, SQL, Technical Process, Excel.",
    "CV_Candidate_2.txt": "Name: Amit. Skills: HTML, CSS, JavaScript, Python.",
    "CV_Candidate_3.txt": "Name: Priya. Skills: Operations, Reporting, Excel, Management.",
    "CV_Candidate_4.txt": "Name: Raj. Skills: Python, Django, SQL, PostgreSQL.",
    "CV_Candidate_5.txt": "Name: Sara. Skills: Python, Scikit-learn, Statistics, SQL."
}

# 2. The Automation (Loop)
for name, content in my_project_files.items():
    with open(name, "w") as f:
        f.write(content)
    print(f"File Generated: {name}")

print("\n--- ALL DATA IS NOW READY IN THE SIDEBAR! ---")

# Step 1: Create an empty bin for Resumes
my_bin = []

# Step 2: 'Append' (drop) your name into the bin
my_bin.append("Babu's Resume")

# Step 3: Look inside the bin to see if it's there
print(my_bin)

# 1. Create our two empty 'bins' for the actual TEXT
job_text_bin = []
resume_text_bin = []

# 2. Our list of all 10 files we created earlier
all_files = [
    "JD_Data_Analyst.txt", "JD_Web_Developer.txt", "JD_Process_Executive.txt", "JD_Python_Dev.txt", "JD_Machine_Learning.txt",
    "CV_Babu.txt", "CV_Candidate_2.txt", "CV_Candidate_3.txt", "CV_Candidate_4.txt", "CV_Candidate_5.txt"
]

# 3. THE LOOP (Our Helper)
for file_name in all_files:

    # Step A: Open and Read the file
    with open(file_name, "r") as f:
        file_content = f.read()  # This grabs the text inside

    # Step B: Decide which bin it belongs in
    if file_name.startswith("JD"):
        job_text_bin.append(file_content)
        print(f"✅ Success: Read {file_name} and put text in JOB bin.")
    else:
        resume_text_bin.append(file_content)
        print(f"📄 Success: Read {file_name} and put text in RESUME bin.")

# 4. The Final Check
print(f"\nSorting Complete! We have {len(job_text_bin)} Jobs and {len(resume_text_bin)} Resumes ready to match.")

# Step 1: Define the skills we are looking for
required_skills = ["python", "sql", "dax", "excel", "communication"]

print("--- STARTING THE RANKING PROCESS ---")

# Step 2: Pick up each resume one by one (The Outer Loop)
for i, resume_text in enumerate(resume_text_bin):

    # RESET the scoreboard for every new candidate
    score = 0

    # Step 3: Check for every skill (The Inner Loop)
    for skill in required_skills:
        if skill in resume_text.lower():
            score = score + 1

    # Step 4: Calculate the percentage (Score / Total Skills * 100)
    percentage = (score / len(required_skills)) * 100

    # Step 5: Show the result for this candidate
    print(f"Candidate {i+1}: Matched {score} skills. Match Score: {percentage}%")

print("--- ALL CANDIDATES RANKED ---")
